### PR TITLE
Terraform 12 compatibility

### PR DESCRIPTION
**Pull request by sheax0r**
This pull request compiles against terraform-0.12, so that this plugin will work with newer versions of terraform.

* Follow instructions from [here](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html) to convert to a module and upgrade the terraform dependency.
* Remove the 'id' fields from resources -- terraform complains if you have these.

The error reported with the id fields present looks like this:

```
Error: Internal validation of the provider failed! This is always a bug
with the provider itself, and not a user issue. Please report
this bug:

2 errors occurred:
	* resource librato_service: id is a reserved field name
	* resource librato_space: id is a reserved field name
```

### CODE REVIEW

**Comment by sheax0r** [comment]
@wchrisjohnson @ricardochimal -- I haven't fully tested this out yet. So far I have only "planned" things with it, I haven't "applied". I noticed you two have committed to this repo, so just tagging y'all in if you're interested in reviewing.

**Comment by mars** [comment]
LGTM 👍

**Comment by bernerdschaefer** [comment]
LGTM.

Hopefully plugins built for 0.12 still work with older terraform versions? Otherwise runtime will have to lock our plugin version and/or be forced to upgrade to 0.12. Both of those are objectively good outcomes, but may not be well-timed! 🤞

**Comment by mars** [comment]
> Hopefully plugins built for 0.12 still work with older terraform versions?

Yes, 0.12 (internal plugin protocol 5) providers do seem to be backward compatible with Terraform 0.10 & 0.11 (internal plugin protocol 4).

**Comment by sheax0r** [comment]
Thanks for having a look @bernerdschaefer and @mars ! 

@bernerdschaefer I tested locally, and I believe that binaries built this way do in fact work with terraform-0.11.

**Pull request merged**
